import React, { useEffect, useState } from 'react';
import { FileText, Pill, Calendar, ChevronDown, ChevronUp, Stethoscope } from 'lucide-react';

const Prescriptions = () => {
    const [prescriptions, setPrescriptions] = useState([]);
    const [loading, setLoading] = useState(true);
    const [expanded, setExpanded] = useState(null);

    useEffect(() => {
        fetchPrescriptions();
    }, []);

    const fetchPrescriptions = async () => {
        const token = localStorage.getItem('token');
        if (!token) return;
        try {
            const res = await fetch('http://localhost:3000/api/prescriptions/my', {
                headers: { 'Authorization': `Bearer ${token}` }
            });
            const data = await res.json();
            if (res.ok) setPrescriptions(data);
        } catch (err) {
            console.error('Error fetching prescriptions:', err);
        } finally {
            setLoading(false);
        }
    };

    const handlePrint = (prescription) => {
        const doctorName = prescription.doctorId?.userId?.name || 'Doctor';
        const patientName = prescription.patientId?.name || 'Patient';
        const date = new Date(prescription.createdAt).toLocaleDateString('en-US', {
            weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
        });

        const printContent = `
            <html><head><title>Prescription</title>
            <style>
                body { font-family: Georgia, serif; max-width: 700px; margin: 40px auto; padding: 30px; color: #111; }
                .header { border-bottom: 3px double #4f46e5; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; }
                .clinic-name { font-size: 24px; font-weight: bold; color: #4f46e5; }
                .rx { font-size: 48px; color: #4f46e5; font-style: italic; }
                table { width: 100%; border-collapse: collapse; margin-top: 16px; }
                th { background: #f0f0ff; padding: 10px; text-align: left; border: 1px solid #ddd; }
                td { padding: 10px; border: 1px solid #ddd; }
                .footer { margin-top: 40px; border-top: 1px solid #ccc; padding-top: 16px; display: flex; justify-content: space-between; }
                .sig { border-top: 1px solid #333; padding-top: 4px; min-width: 180px; text-align: center; font-size: 12px; }
            </style></head>
            <body>
            <div class="header">
                <div>
                    <div class="clinic-name">MediConnect</div>
                    <div>Dr. ${doctorName}</div>
                    <div>Issued: ${date}</div>
                </div>
                <div class="rx">Rx</div>
            </div>
            <p><strong>Patient:</strong> ${patientName}</p>
            <p><strong>Diagnosis:</strong> ${prescription.diagnosis}</p>
            <h3>Medicines</h3>
            <table>
                <thead><tr><th>#</th><th>Medicine</th><th>Dosage</th><th>Frequency</th><th>Duration</th></tr></thead>
                <tbody>
                ${prescription.medicines.map((m, i) => `
                    <tr><td>${i + 1}</td><td>${m.name}</td><td>${m.dosage}</td><td>${m.frequency}</td><td>${m.duration}</td></tr>
                `).join('')}
                </tbody>
            </table>
            ${prescription.instructions ? `<p style="margin-top:16px"><strong>Instructions:</strong> ${prescription.instructions}</p>` : ''}
            ${prescription.followUpDate ? `<p><strong>Follow-up Date:</strong> ${new Date(prescription.followUpDate).toLocaleDateString()}</p>` : ''}
            <div class="footer">
                <div class="sig">Dr. ${doctorName}<br/>Signature</div>
                <div style="font-size:12px; color:#888;">Generated by MediConnect &bull; For informational purposes only</div>
            </div>
            </body></html>`;

        const win = window.open('', '_blank');
        win.document.write(printContent);
        win.document.close();
        win.print();
    };

    if (loading) return <div className="p-8 text-center text-gray-400">Loading prescriptions...</div>;

    return (
        <div className="space-y-6 animate-fade-in-up">
            <div className="flex items-center gap-3">
                <div className="p-2 bg-purple-100 rounded-lg">
                    <FileText className="w-6 h-6 text-purple-600" />
                </div>
                <h2 className="text-2xl font-bold text-gray-800">My Prescriptions</h2>
            </div>

            {prescriptions.length === 0 ? (
                <div className="bg-white rounded-2xl shadow-sm border border-lavender-100 p-12 text-center">
                    <FileText className="w-14 h-14 text-gray-200 mx-auto mb-4" />
                    <p className="text-gray-400 font-medium">No prescriptions yet.</p>
                    <p className="text-gray-300 text-sm mt-1">Your doctor's prescriptions will appear here after your consultation.</p>
                </div>
            ) : (
                <div className="space-y-4">
                    {prescriptions.map((rx) => (
                        <div key={rx._id} className="bg-white rounded-2xl shadow-sm border border-lavender-100 overflow-hidden hover:shadow-md transition-all">
                            {/* Card Header */}
                            <div className="p-5 flex items-center justify-between">
                                <div className="flex items-center gap-4">
                                    <div className="w-12 h-12 rounded-xl bg-purple-50 flex items-center justify-center">
                                        <Stethoscope className="w-6 h-6 text-purple-600" />
                                    </div>
                                    <div>
                                        <h3 className="font-bold text-gray-800">
                                            Dr. {rx.doctorId?.userId?.name || 'Doctor'}
                                        </h3>
                                        <p className="text-sm text-gray-500">{rx.diagnosis}</p>
                                        <div className="flex items-center gap-1 text-xs text-gray-400 mt-1">
                                            <Calendar className="w-3 h-3" />
                                            {new Date(rx.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}
                                        </div>
                                    </div>
                                </div>
                                <div className="flex items-center gap-2">
                                    <button
                                        onClick={() => handlePrint(rx)}
                                        className="px-4 py-1.5 text-xs bg-lavender-50 text-lavender-700 hover:bg-lavender-100 rounded-lg font-medium transition-colors"
                                    >
                                        Print / Download
                                    </button>
                                    <button
                                        onClick={() => setExpanded(expanded === rx._id ? null : rx._id)}
                                        className="p-2 rounded-lg hover:bg-gray-50 transition-colors"
                                    >
                                        {expanded === rx._id ? <ChevronUp className="w-5 h-5 text-gray-400" /> : <ChevronDown className="w-5 h-5 text-gray-400" />}
                                    </button>
                                </div>
                            </div>

                            {/* Expanded Details */}
                            {expanded === rx._id && (
                                <div className="border-t border-gray-100 p-5 bg-gray-50 space-y-4">
                                    {/* Medicines Table */}
                                    <div>
                                        <h4 className="font-semibold text-gray-700 text-sm mb-3 flex items-center gap-1">
                                            <Pill className="w-4 h-4 text-purple-500" /> Medicines
                                        </h4>
                                        <div className="overflow-x-auto rounded-xl border border-gray-200">
                                            <table className="w-full text-sm">
                                                <thead className="bg-white">
                                                    <tr className="border-b border-gray-100">
                                                        <th className="text-left p-3 text-gray-500 font-medium">Medicine</th>
                                                        <th className="text-left p-3 text-gray-500 font-medium">Dosage</th>
                                                        <th className="text-left p-3 text-gray-500 font-medium">Frequency</th>
                                                        <th className="text-left p-3 text-gray-500 font-medium">Duration</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {rx.medicines.map((med, i) => (
                                                        <tr key={i} className={`border-b border-gray-50 ${i % 2 === 0 ? 'bg-white' : 'bg-gray-50'}`}>
                                                            <td className="p-3 font-medium text-gray-800">{med.name}</td>
                                                            <td className="p-3 text-gray-600">{med.dosage}</td>
                                                            <td className="p-3 text-gray-600">{med.frequency}</td>
                                                            <td className="p-3 text-gray-600">{med.duration}</td>
                                                        </tr>
                                                    ))}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>

                                    {rx.instructions && (
                                        <div className="bg-amber-50 border border-amber-100 rounded-xl p-4">
                                            <p className="text-xs font-semibold text-amber-700 uppercase tracking-wider mb-1">Doctor's Instructions</p>
                                            <p className="text-sm text-amber-800">{rx.instructions}</p>
                                        </div>
                                    )}

                                    {rx.followUpDate && (
                                        <div className="flex items-center gap-2 text-sm text-gray-600 bg-blue-50 p-3 rounded-xl border border-blue-100">
                                            <Calendar className="w-4 h-4 text-blue-500" />
                                            <span>Follow-up scheduled: <strong>{new Date(rx.followUpDate).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</strong></span>
                                        </div>
                                    )}
                                </div>
                            )}
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
};

export default Prescriptions;
